### PR TITLE
add key and door support for jungle scene

### PR DESCRIPTION
**Pull request by sahara2001**

### CODE REVIEW

**Comment by snnn333** [comment]
Warning
image

**Comment by snnn333** [comment]
Warning when running
image

**Comment by sahara2001** [comment]
F:\project\526_merge1>git merge origin/main
error: unable to create file Assets/Models/526week4models /526_week4_models.unity: No such file or directory
error: unable to create file Assets/Models/526week4models /526_week4_models.unity.meta: No such file or directory

**Comment by sahara2001** [comment]
need to resolve the error above when merging main branch

**Review by fanzhangg — APPROVED** [review]
Nice work! Interesting level design and polished prop mechanisms. Be cautious when merging it to the mainline as there are tons of changes

**Pull request merged**
